export const it = {
  nav: {
    title: 'Atlante di Sherdan',
    campaign: 'Campagna',
    characters: 'Personaggi',
    sessions: 'Sessioni',
    map: 'Mappa',
    gallery: 'Galleria',
    login: 'Accedi',
    admin: 'Admin',
    adminDashboard: 'Pannello admin',
    logout: 'Esci',
  },

  home: {
    defaultTitle: 'Campagna Pirata',
    defaultTagline: 'Un’avventura ti attende in alto mare',
    beginAdventure: 'Inizia l’avventura',
    meetCrew: 'Conosci l’equipaggio',
    scroll: 'Scorri',
  },

  campaign: {
    loading: 'Caricamento campagna...',
    empty: 'Informazioni sulla campagna in arrivo!',
    worldLoreTab: 'Lore del mondo',
    storyArcTab: 'Arco narrativo',
    houseRulesTab: 'Regole della campagna',
    worldLoreTitle: 'Lore del mondo',
    worldLoreEmpty: 'Nessuna lore è stata ancora registrata...',
    storyTitle: 'Arco narrativo principale',
    storyEmpty: 'La storia deve ancora essere scritta...',
    rulesTitle: 'Regole della campagna',
    rulesEmpty: 'Non sono ancora state definite regole speciali...',
  },

  charactersPublic: {
    title: 'L’equipaggio',
    subtitle: 'Incontra gli avventurieri della leggenda',
    loading: 'Caricamento personaggi...',
    empty: 'Nessun personaggio ancora. Torna presto!',
    level: 'Livello',
    class: 'Classe',
    race: 'Razza',
    backstory: 'Storia',
  },

  sessionsPublic: {
    title: 'Cronache di sessione',
    subtitle: 'Racconti dall’alto mare',
    loading: 'Caricamento sessioni...',
    empty: 'Nessun registro di sessione ancora. La storia inizierà presto...',
    session: 'Sessione',
    summary: 'Riassunto',
    fullAccount: 'Resoconto completo',
  },

  mapPublic: {
    title: 'Mappa del mondo',
    subtitle: 'Esplora il mondo conosciuto e oltre',
    loading: 'Caricamento mappa...',
    locations: 'Luoghi',
    type: 'Tipo',
    control: 'Controllo',
    description: 'Descrizione',
    history: 'Storia',
    coordinates: 'Coordinate',
    worldMapAlt: 'Mappa del mondo',
    locationTypes: {
      port: 'Porto',
      island: 'Isola',
      territory: 'Territorio',
      landmark: 'Punto di interesse',
    },
    controlStatuses: {
      neutral: 'Neutrale',
      player_controlled: 'Controllato dai giocatori',
      enemy_controlled: 'Controllato dai nemici',
      allied: 'Alleato',
    },
  },

  galleryPublic: {
    title: 'Galleria della campagna',
    subtitle: 'Momenti dall’alto mare',
    loading: 'Caricamento galleria...',
    empty: 'Nessuna immagine ancora. I momenti epici arriveranno presto!',
    of: 'di',
  },

  admin: {
    panel: 'Pannello Admin',
    dashboard: 'Dashboard',
    characters: 'Personaggi',
    sessions: 'Sessioni',
    locations: 'Luoghi',
    gallery: 'Galleria',
    settings: 'Impostazioni campagna',
    backToSite: '← Torna al sito',
    logout: 'Esci',
  },

  dashboard: {
    title: 'Dashboard della campagna',
    loading: 'Caricamento...',
    quickLinks: 'Collegamenti rapidi',
    welcomeTitle: 'Benvenuto, Capitano!',
    welcomeText:
      'Usa il pannello admin per gestire ogni aspetto della campagna. Aggiungi personaggi, registra sessioni, posiziona luoghi sulla mappa e carica immagini in galleria. Tutte le modifiche vengono salvate nel database e appaiono sul sito pubblico in tempo reale.',
    stats: {
      characters: 'Personaggi',
      sessions: 'Sessioni',
      locations: 'Luoghi',
      galleryItems: 'Elementi galleria',
    },
    cards: {
      charactersTitle: 'Gestisci personaggi',
      charactersText: 'Aggiungi, modifica o rimuovi i personaggi dei giocatori',
      sessionsTitle: 'Gestisci sessioni',
      sessionsText: 'Crea e aggiorna i registri delle sessioni',
      locationsTitle: 'Gestisci luoghi',
      locationsText: 'Aggiungi marker e territori sulla mappa',
      galleryTitle: 'Gestisci galleria',
      galleryText: 'Carica e organizza le immagini',
      settingsTitle: 'Impostazioni campagna',
      settingsText: 'Modifica lore del mondo e regole',
    },
  },

  adminCharacters: {
    title: 'Personaggi',
    add: 'Aggiungi personaggio',
    addNew: 'Aggiungi nuovo personaggio',
    edit: 'Modifica personaggio',
    loading: 'Caricamento personaggi...',
    empty: 'Nessun personaggio ancora. Creane uno per iniziare!',
    confirmDelete: 'Sei sicuro di voler eliminare questo personaggio?',
    fields: {
      name: 'Nome',
      class: 'Classe',
      race: 'Razza',
      level: 'Livello',
      backstory: 'Storia',
      portraitUrl: 'URL ritratto',
    },
    actions: {
      create: 'Crea personaggio',
      update: 'Aggiorna personaggio',
      cancel: 'Annulla',
    },
  },

  adminSessions: {
    title: 'Registri sessione',
    add: 'Aggiungi sessione',
    addNew: 'Aggiungi nuova sessione',
    edit: 'Modifica sessione',
    loading: 'Caricamento sessioni...',
    empty: 'Nessuna sessione ancora. Crea il tuo primo registro!',
    confirmDelete: 'Sei sicuro di voler eliminare questa sessione?',
    sessionLabel: 'Sessione',
    fields: {
      sessionNumber: 'Numero sessione',
      title: 'Titolo',
      date: 'Data',
      summary: 'Riassunto',
      detailedNarrative: 'Narrazione dettagliata',
      featuredImageUrl: 'URL immagine in evidenza',
    },
    actions: {
      create: 'Crea sessione',
      update: 'Aggiorna sessione',
      cancel: 'Annulla',
    },
  },

  adminLocations: {
    title: 'Luoghi della mappa',
    add: 'Aggiungi luogo',
    addNew: 'Aggiungi nuovo luogo',
    edit: 'Modifica luogo',
    loading: 'Caricamento luoghi...',
    empty: 'Nessun luogo ancora. Aggiungi alcuni punti di interesse alla mappa!',
    confirmDelete: 'Sei sicuro di voler eliminare questo luogo?',
    coords: 'Coordinate',
    fields: {
      name: 'Nome del luogo',
      description: 'Descrizione',
      type: 'Tipo',
      controlStatus: 'Stato di controllo',
      x: 'Coordinata X',
      y: 'Coordinata Y',
      history: 'Storia (opzionale)',
    },
    types: {
      port: 'Porto',
      island: 'Isola',
      territory: 'Territorio',
      landmark: 'Punto di interesse',
    },
    statuses: {
      neutral: 'Neutrale',
      player_controlled: 'Controllato dai giocatori',
      enemy_controlled: 'Controllato dai nemici',
      allied: 'Alleato',
    },
    actions: {
      create: 'Crea luogo',
      update: 'Aggiorna luogo',
      cancel: 'Annulla',
    },
  },

  adminGallery: {
    title: 'Galleria',
    add: 'Aggiungi immagine',
    formTitle: 'Aggiungi immagine',
    loading: 'Caricamento galleria...',
    empty: 'Nessuna immagine ancora. Aggiungi qualche ricordo della campagna!',
    confirmDelete: 'Sei sicuro di voler eliminare questa immagine?',
    preview: 'Anteprima',
    noSession: 'Nessuna sessione',
    session: 'Sessione',
    fields: {
      imageUrl: 'URL immagine',
      title: 'Titolo',
      description: 'Descrizione',
      category: 'Categoria',
    },
    actions: {
      addToGallery: 'Aggiungi alla galleria',
      cancel: 'Annulla',
    },
  },

  adminSettings: {
    title: 'Impostazioni campagna',
    loading: 'Caricamento impostazioni...',
    loadError: 'Impossibile caricare le impostazioni',
    saveSuccess: 'Impostazioni salvate con successo!',
    saveError: 'Salvataggio delle impostazioni non riuscito',
    saving: 'Salvataggio in corso...',
    save: 'Salva impostazioni campagna',
    fields: {
      campaignTitle: 'Titolo campagna',
      campaignTagline: 'Sottotitolo campagna',
      worldLore: 'Lore del mondo',
      mainStoryArc: 'Arco narrativo principale',
      houseRules: 'Regole della campagna',
    },
    placeholders: {
      worldLore: 'Descrivi il mondo e la sua storia...',
      mainStoryArc: 'Descrivi la narrazione principale...',
      houseRules: 'Elenca le regole speciali di questa campagna...',
    },
    defaults: {
      title: 'Campagna Pirata',
      tagline: 'Un’avventura ti attende in alto mare',
    },
  },

  login: {
    title: 'Diario del Capitano',
    subtitle: 'Accedi per gestire la tua campagna',
    email: 'Email',
    password: 'Password',
    submit: 'Accedi',
    loading: 'Accesso in corso...',
    error: 'Accesso non riuscito',
    signupPrompt: 'Non hai un account?',
    signupAction: 'Creane uno',
    emailPlaceholder: 'capitano@mare.it',
  },

  signup: {
    title: 'Unisciti all’equipaggio',
    subtitle: 'Crea il tuo account admin',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Conferma password',
    emailPlaceholder: 'capitano@mare.it',
    errors: {
      passwordMismatch: 'Le password non coincidono',
      passwordLength: 'La password deve contenere almeno 6 caratteri',
      generic: 'Creazione account non riuscita',
    },
    submit: 'Crea account',
    loading: 'Creazione account...',
    loginPrompt: 'Hai già un account?',
    loginAction: 'Accedi',
  },

  footer: {
    title: 'Campagna d’alto mare 2026',
    subtitle: 'Dove le leggende vengono forgiate tra fuoco e furia',
    contactLabel: 'Contatto',
    chronicle: 'Cronache della campagna di D&D',
  },
};
